### PR TITLE
add api file

### PR DESCRIPTION
**Pull request by peichang6**
add api file

### CODE REVIEW

**Comment by peichang6** [comment]
discord: Phoebe
http://18.180.133.88:3000/api/attractions?page=0
http://18.180.133.88:3000/api/attractions?page=0&keyword=藝術
http://18.180.133.88:3000/api/attraction/21
http://18.180.133.88:3000/api/attraction/100

**Comment by cwpeng** [comment]
Your database connection is lost for now, recover your server and leave comment for me to review again.

**Comment by peichang6** [comment]
I've connected the server by ssh and try Nohup again, then turn off my terminal.
The page seems to work now.
But I have no idea why the database was lost....

**Review by cwpeng — APPROVED** [review]
Basically OK. Done.

Suggestion: It's disconnected by MySQL because long time of idle. Connection pool can prevent this. But you do not use connection pool in a right way. We should follow steps: 1. create pool at server started. 2. get connection from pool in every request, use it and close it. 

I mean code below should be put in the route function and close (return to pool) in the end.
```
mydb = connection_pool.get_connection()
mycursor = mydb.cursor(dictionary=True)
```

**Comment by peichang6** [comment]
Got it!!!
Thanks for the helpful advice : )

**Pull request merged**
