### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by peichang6**
Phoebe
http://18.180.133.88:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Aspect ratio (長寬比) of background image of key visual section is broken, should keep the same as original image in any devices.
2. Attraction list contain only 4 columns per row in larger devices. (>1200px.) Try to test using developer tools if your screen size is not large enough.

Fix issues and leave comment for me to review again.

未命名-3
未命名-5

**Comment by peichang6** [comment]
update the CSS to fix the issue...

**Comment by cwpeng** [comment]
But new issue: content should be align left and right with each other within 1200px width in large devices. (>1200px)

未命名-2

**Comment by peichang6** [comment]
update again 
please help to check if any issue, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
